### ISSUE TITLE
ready doesn't fire in angular 1.0.7?

### ISSUE THREAD

**Issue by laurelnaiad** [laurelnaiad/angular-couch-potato#2]

**Comment by nissoh** [comment]
The examples seems to work fine.

i had an issue because i was bootstrapping everything with require instead of script tags.

**Comment by laurelnaiad** [comment]
Bootstrapping with require should work, too. I have some updates and will include a sample of that.

**Comment by nissoh** [comment]
i modified your code to run on require bootstrap with angular 1.07. this issue still occurs often.
i can push a branch with my code if you want.

p.s. it works fine on rc version

**Comment by laurelnaiad** [comment]
I am indeed curious why you needed to modify anything to use requirejs using the angular bootstrap method.... you should be able to shim couch-potato with a dependency of angular and be good to go.  If you can either show me what you changed or tell me why you needed to do it, it might help me out! Thanks.

**Comment by laurelnaiad** [comment]
I'll close this unless we can demonstrate a problem.
