### ISSUE TITLE
super lazy : both html and js

### ISSUE THREAD

**Issue by navinSing** [laurelnaiad/angular-couch-potato#20]
hot do lazy load the js routes and its template html lazily and dynamically from server side.

this means that if the url[state] is not found locally. It will query the server lets say findRoute(name:'abc')  which returns json, js of state, template html; which will be injected into crouch-potato and served to the client.

**Comment by laurelnaiad** [comment]
Hi... I'm not sure I'm following you, but it sort of sounds like you're describing a feature of https://github.com/afterglowtech/angular-detour .. but please be aware that both couch-potato and detour are a bit dated and won't have any new development.
