### ISSUE TITLE
where is server.js?

### ISSUE THREAD

**Issue by GoNode5** [laurelnaiad/angular-couch-potato#6]
Thanks for the great lib. If I follow the sample README.md i cant find the server.js?

cd into components-demo or ui-router-sample
node server.js

**Comment by laurelnaiad** [comment]
Sorry about that -- the local samples' server didn't get updated after they were refactored.  Please try cloning again (or pulling the latest commit).  I've also updated the [samples README](https://github.com/stu-salsbury/angular-couch-potato/blob/master/samples/README.md) with new instructions.  I'll close this -- if you have any trouble please post a new issue.  Thanks for the heads up.
