### ISSUE TITLE
What about the documentation?

### ISSUE THREAD

**Issue by hackdan** [laurelnaiad/angular-couch-potato#7]
The documentation is missing the sref in the internal links of each section of the guide, so is a potato couch's problem or just is because de documentation is in progress yet?. However cheroois by u project is AMAZING!, how can i involve in with him more ?. My target is make a huuuuugeeeee app, but i really not understand at all, how can i write it in a collaborative way?. I'm tried say:  With a team in a huge app  within  a ui-router how this would configure dinamically the stateProvider when others developers comes to contribute with something new and then will write in a stateprovider path of router, manually?.

**Comment by laurelnaiad** [comment]
Yes, the documentation is very much a work unfinished.   Sorry about that.  As I was documenting I came up with some ideas based on new features of UI-router that I'd like to try out before I document the present behavior any further.

As to making a huge app with multiple collaborators who do not necessarily coordinate completely with each other, there is https://github.com/afterglowtech/angular-detour .  Among other things, it allows routing to be driven by a server -- and that "main" server may collect "pieces" of the routing from anywhere it likes and assemble them such that the browser sees one app even if the pieces come from different servers.  If you like the Couch Potato Docs, you _love_ the Detour docs... :)  Can't even really call them a work unfinished, yet.

With just Couch Potato alone, you can specify dependencies that come from different servers or different places on your server, and you can allow different authors to author different components, but you still need a centralized routing definition for $stateProvider (given that you seem to be using ui-router).

Hope that helps... I'll close this but feel free to ask more questions should you have them.

**Comment by hackdan** [comment]
MANY THANKS, I WILL KEEP PENDANT FOR THE NEWS!
