### ISSUE TITLE
Guidance on how to get Directives in

### ISSUE THREAD

**Issue by ghstahl** [laurelnaiad/angular-couch-potato#9]
This is all based upon your ui-router sample where I got your stuff as written to work.  Now unto my stuff :0
I tried adding paths to my directives as follows in routeDefs.js and they were not picked up by the view.

resolve: {
                    dummy: $couchPotatoProvider.resolveDependencies([
                        'controllers/ContactViewController',
                        'directives/app-color',
                    ]),
I then put them in the require define in the routeDefs.js and then they worked in my view.
define([
    'app',
    'directives/app-color'
], function(app) {...}

any clue as to why the require in your $couchPotatoProvider.resolveDependencies gets the controller to work but the directives aren't coming in?

This is really a broader question where I would like to bring in a bunch of stuff for the route, like services, factories, directives, etc.

Thanks
H

**Comment by laurelnaiad** [comment]
All types of components will work the same -- and for the purposes of couch potato anything you try to load via the resolveDependencies process needs to be `define`d somewhere.  If you'd like me to help you figure out what's going on, you can post a [plunker](http://plnkr.co), and I'll take a look.

**Comment by ghstahl** [comment]
ghstahl @ gmail

​http://plnkr.co/edit/LP8Jmi9eWWNYlMbhP7h2?p=preview

note: my javascript/angular skills are a working in progress, so I suspect
that this is a bonehead mistake on my part.

I am trying to build a dynamic form module, via Frankensteining together
the good works of others.

Thanks
Herb

**Comment by laurelnaiad** [comment]
Wow, I didn't expect your entire app in the plunker... can you make a _small_ pliunker that isolates what you're trying to do?  I'll close this for now, as I just can't be diving into such a massive amount of code to help you out.
